/** Food & drink emojis with names for search (used in product form and save-product modal). */
export const EMOJI_PICKER_LIST: Array<{ emoji: string; name: string }> = [
  { emoji: '🍎', name: 'appel' },
  { emoji: '🍐', name: 'peer' },
  { emoji: '🍊', name: 'sinaasappel' },
  { emoji: '🍋', name: 'citroen' },
  { emoji: '🍌', name: 'banaan' },
  { emoji: '🍉', name: 'watermeloen' },
  { emoji: '🍇', name: 'druiven' },
  { emoji: '🍓', name: 'aardbei' },
  { emoji: '🍑', name: 'perzik' },
  { emoji: '🍒', name: 'kersen' },
  { emoji: '🥝', name: 'kiwi' },
  { emoji: '🥭', name: 'mango' },
  { emoji: '🍍', name: 'ananas' },
  { emoji: '🥥', name: 'kokosnoot' },
  { emoji: '🫐', name: 'blauwe bes' },
  { emoji: '🍈', name: 'meloen' },
  { emoji: '🫒', name: 'olijf' },
  { emoji: '🍆', name: 'aubergine' },
  { emoji: '🍅', name: 'tomaat' },
  { emoji: '🥑', name: 'avocado' },
  { emoji: '🥒', name: 'komkommer' },
  { emoji: '🥕', name: 'wortel' },
  { emoji: '🌽', name: 'maïs' },
  { emoji: '🌶️', name: 'peper' },
  { emoji: '🫑', name: 'paprika' },
  { emoji: '🥬', name: 'bladgroente' },
  { emoji: '🥦', name: 'broccoli' },
  { emoji: '🫛', name: 'erwten' },
  { emoji: '🫚', name: 'gember' },
  { emoji: '🧄', name: 'knoflook' },
  { emoji: '🧅', name: 'ui' },
  { emoji: '🥔', name: 'aardappel' },
  { emoji: '🍠', name: 'zoete aardappel' },
  { emoji: '🥜', name: 'pinda' },
  { emoji: '🌰', name: 'kastanje' },
  { emoji: '🍄', name: 'champignon' },
  { emoji: '🍞', name: 'brood' },
  { emoji: '🥐', name: 'croissant' },
  { emoji: '🥖', name: 'stokbrood' },
  { emoji: '🥨', name: 'pretzel' },
  { emoji: '🥯', name: 'bagel' },
  { emoji: '🧇', name: 'wafel' },
  { emoji: '🥞', name: 'pannenkoek' },
  { emoji: '🧀', name: 'kaas' },
  { emoji: '🥚', name: 'ei' },
  { emoji: '🍳', name: 'gebakken ei' },
  { emoji: '🥓', name: 'spek' },
  { emoji: '🥩', name: 'vlees' },
  { emoji: '🍗', name: 'kip' },
  { emoji: '🍖', name: 'vlees aan bot' },
  { emoji: '🦐', name: 'garnaal' },
  { emoji: '🦞', name: 'kreeft' },
  { emoji: '🦀', name: 'krab' },
  { emoji: '🦑', name: 'inktvis' },
  { emoji: '🐙', name: 'octopus' },
  { emoji: '🐟', name: 'vis' },
  { emoji: '🍤', name: 'gefrituurde garnaal' },
  { emoji: '🥟', name: 'dumpling' },
  { emoji: '🌭', name: 'hotdog' },
  { emoji: '🍔', name: 'hamburger' },
  { emoji: '🍟', name: 'friet' },
  { emoji: '🍕', name: 'pizza' },
  { emoji: '🥪', name: 'sandwich' },
  { emoji: '🌮', name: 'taco' },
  { emoji: '🌯', name: 'burrito' },
  { emoji: '🥙', name: 'gevulde pita' },
  { emoji: '🧆', name: 'falafel' },
  { emoji: '🥘', name: 'stoofpot' },
  { emoji: '🥗', name: 'salade' },
  { emoji: '🍲', name: 'pot eten' },
  { emoji: '🍝', name: 'spaghetti' },
  { emoji: '🍜', name: 'noedels' },
  { emoji: '🍛', name: 'curry rijst' },
  { emoji: '🍣', name: 'sushi' },
  { emoji: '🍱', name: 'bento box' },
  { emoji: '🍚', name: 'rijst' },
  { emoji: '🍙', name: 'rijstbal' },
  { emoji: '🍫', name: 'chocolade' },
  { emoji: '🍩', name: 'donut' },
  { emoji: '🍪', name: 'koekje' },
  { emoji: '🍯', name: 'honing' },
  { emoji: '🥛', name: 'glas melk' },
  { emoji: '☕', name: 'koffie' },
  { emoji: '🫖', name: 'theepot' },
  { emoji: '🍵', name: 'thee' },
  { emoji: '🧋', name: 'bubble tea' },
  { emoji: '🍷', name: 'wijn' },
  { emoji: '🥤', name: 'beker met rietje' },
  { emoji: '🧊', name: 'ijsklontje' },
  { emoji: '🫙', name: 'pot' },
  { emoji: '🧂', name: 'zout' },
  { emoji: '🛒', name: 'winkelwagen' },
  { emoji: '🧼', name: 'zeep' },
  { emoji: '🧴', name: 'lotion' },
  { emoji: '🪥', name: 'tandenborstel' },
  { emoji: '🧻', name: 'wc-papier' },
]
